"""
data/schema.py — Pydantic v2 request / response schemas for betatp.io

All models use pydantic v2 (BaseModel from pydantic).
Separate from the SQLAlchemy ORM layer (data/models.py).
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ──────────────────────────────────────────────────────────────────────────────
# Core domain schemas
# ──────────────────────────────────────────────────────────────────────────────


class MatchSchema(BaseModel):
    """Represents a tennis match (read / write)."""

    id: Optional[str] = None
    date: Optional[date] = None
    player_a: Optional[str] = None
    player_b: Optional[str] = None
    surface: Optional[str] = None
    tourney_level: Optional[str] = None
    score: Optional[str] = None
    winner: Optional[str] = None

    model_config = {"from_attributes": True}


class PlayerSchema(BaseModel):
    """Represents an ATP player."""

    id: Optional[int] = None
    name: str
    country: Optional[str] = None
    dob: Optional[date] = None

    model_config = {"from_attributes": True}


# ──────────────────────────────────────────────────────────────────────────────
# Betting / value schemas
# ──────────────────────────────────────────────────────────────────────────────


class SelectionSchema(BaseModel):
    """A single bet selection within a coupon."""

    match_id: str
    player: str
    odds: float = Field(..., ge=1.0, description="Decimal odds (must be ≥ 1.0)")
    p_model: float = Field(
        ..., ge=0.0, le=1.0, description="Model win probability for this player"
    )
    ev: float = Field(..., description="Expected value: p_model * odds - 1")
    kelly_stake_pct: float = Field(
        ..., ge=0.0, le=1.0, description="Kelly criterion stake as fraction of bankroll"
    )
    reasoning: Optional[str] = Field(
        None, description="Human-readable reasoning for this selection"
    )

    @field_validator("ev", mode="before")
    @classmethod
    def _validate_ev(cls, v: float) -> float:
        return round(float(v), 6)

    @field_validator("kelly_stake_pct", mode="before")
    @classmethod
    def _clamp_kelly(cls, v: float) -> float:
        return max(0.0, min(1.0, float(v)))


class CouponSchema(BaseModel):
    """A coupon grouping one or more selections."""

    id: Optional[str] = None
    date: Optional[date] = None
    coupon_type: Literal["single", "system"] = "single"
    selections: list[SelectionSchema] = Field(default_factory=list)
    ev: float = Field(0.0, description="Aggregate expected value of the coupon")
    status: Literal["pending", "won", "lost"] = "pending"

    @model_validator(mode="after")
    def _check_selections(self) -> "CouponSchema":
        if self.coupon_type == "single" and len(self.selections) > 1:
            raise ValueError(
                "A 'single' coupon must have at most 1 selection; "
                f"got {len(self.selections)}."
            )
        return self

    model_config = {"from_attributes": True}


class BetSchema(BaseModel):
    """Records a user's placed bet against a coupon."""

    user_id: int
    coupon_id: str
    stake: float = Field(..., gt=0.0, description="Stake amount in user currency")
    opening_odds: float = Field(..., ge=1.0)
    closing_odds: Optional[float] = Field(None, ge=1.0)
    clv: Optional[float] = Field(
        None,
        description="Closing-line value: (opening_odds / closing_odds) - 1",
    )
    pnl: Optional[float] = Field(None, description="Profit & loss (post-settlement)")

    model_config = {"from_attributes": True}


class AlertSchema(BaseModel):
    """Value alert generated by the EV scanner."""

    match_id: str
    player: str
    ev_pct: float = Field(..., description="Expected value as a percentage (e.g. 0.05 = 5%)")
    priority: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = "MEDIUM"
    alert_type: Literal["pre_match", "in_play", "derivative"] = "pre_match"
    created_at: datetime = Field(default_factory=datetime.utcnow)

    model_config = {"from_attributes": True}


# ──────────────────────────────────────────────────────────────────────────────
# API request / response schemas
# ──────────────────────────────────────────────────────────────────────────────


class CouponRequest(BaseModel):
    """
    User-facing coupon generation request.

    Filters control which selections are considered:
      - min_ev: minimum expected value threshold (e.g. 0.02 = +2% EV)
      - min_odds / max_odds: odds range filter
      - max_selections: cap on number of legs
    """

    min_ev: float = Field(
        default=0.02,
        ge=0.0,
        description="Minimum EV threshold for a selection to be included",
    )
    min_odds: float = Field(
        default=1.30,
        ge=1.0,
        description="Minimum decimal odds for a selection",
    )
    max_odds: float = Field(
        default=5.00,
        ge=1.0,
        description="Maximum decimal odds for a selection",
    )
    max_selections: int = Field(
        default=3,
        ge=1,
        le=20,
        description="Maximum number of selections in the coupon",
    )

    @model_validator(mode="after")
    def _check_odds_range(self) -> "CouponRequest":
        if self.min_odds > self.max_odds:
            raise ValueError(
                f"min_odds ({self.min_odds}) must be ≤ max_odds ({self.max_odds})"
            )
        return self


class PredictionResponse(BaseModel):
    """
    Slimmed-down prediction result returned to the API consumer.
    For the full object (with mc_outputs etc.) use PreMatchPredictor directly.
    """

    player_a: str
    player_b: str
    p_win_a: float = Field(..., ge=0.0, le=1.0)
    p_win_b: float = Field(..., ge=0.0, le=1.0)
    elo_diff: float
    confidence: Literal["low", "medium", "high"]

    @model_validator(mode="after")
    def _check_probs_sum(self) -> "PredictionResponse":
        total = self.p_win_a + self.p_win_b
        if not (0.99 <= total <= 1.01):
            raise ValueError(
                f"p_win_a + p_win_b should sum to ~1.0, got {total:.6f}"
            )
        return self
